controllers:
    resource: ../src/Controller/
    type: attribute

number:

  path: /number

  controller: App\Controller\Controller::number

index:
  path: /
  controller: App\Controller\Controller::index
